name: Thrust
favicon: null
layout_spectrum: 0.5808488309849054
typography_spectrum: 0.9662764954846352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6824126809369773
  lightness: 0.8297565649263561
  saturation: 0.07372233760543168
  rhythmicContrast: 0.22939120954833925
purpose: []
