name: Thrust
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9662764954846352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#343433'
    - '#f89921'
    - '#f1592a'
    - '#999999'
    - '#cecece'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
